### ISSUE TITLE
Remove .DS_Store

### ISSUE THREAD

**Issue by r0mainK** [iterative/aita_dataset#2]
Hey ! 

So first things first, you forgot to add `.DS_Store` to your `.gitignore` (I would usually PR, but not sure you want contributions on corporate repos ?).
 
More importantly, thank you for the blog post (and the dataset) :) We've been looking at DVC in my team these past couple days, and your blog plost showcases really well it's pros and usage.

Anyway, cheers

**Comment by elleobrien** [comment]
you're right! and we don't mind any PRs ;)

thanks for the kind words and be in touch if we can help with anything for your team.
